### PR TITLE
blas/netlib: run go generate

### PR DESCRIPTION
**Pull request by vladimir-ch**

### CODE REVIEW

**Comment by vladimir-ch** [comment]
I have sneaked in a fix for slice length check in ?gbmv. The tests don't panic now but still fail. I'll take a look at what's causing it.

**Comment by vladimir-ch** [comment]
Argh, my master was not up to date. But the test is still failing for me.

**Comment by kortschak** [comment]
What is happening here? I don't see the change to gbmv?

**Comment by vladimir-ch** [comment]
There is none, it was same as what you merged a few days ago. So this PR is just the comments for complex blas.

**Pull request merged**
