### PR TITLE
lapack/netlib: require Gonum v0.13 and add missing methods

### LINKED ISSUE #91: lapack/netlib/lapack.go: Missing implementation of method Dlampr
When trying to install the netlib package i get this error : # [gonum.org/v1/netlib/lapack/netlib](http://gonum.org/v1/netlib/lapack/netlib)
../../../go/pkg/mod/[gonum.org/v1/netlib@v0.0.0-20220323200511-14de99971b2d/lapack/netlib/lapack.go:19:24](http://gonum.org/v1/netlib@v0.0.0-20220323200511-14de99971b2d/lapack/netlib/lapack.go:19:24): cannot use Implementation{} (value of type Implementation) as lapack.Float64 value in variable declaration: Implementation does not implement lapack.Float64 (missing method Dlapmr)
-the error seems to come from the gonum version required by netlib (v0.8.1-0.20200930085651-eea0b5cb5cc9) since the method Dlampr was added after v 0.11.0 , so it's fixed by holding the gonum to v0.11.0 or above

### PR DESCRIPTION
**Pull request by vladimir-ch**
Let's give some TLC to the netlib packages. Let's start by requiring Gonum v0.13 and adding missing methods which are `Dlapmr` and `Dpstrf`. The editor reformatted comments on save and I also removed two unreachable returns that somehow sneaked in in the past.

Unfortunately, there are two failing tests: one in BLAS `Drotg` (new one) and one in LAPACK `Dlarfb`. I should probably identify the root cause before merging this.

Fixes #91

Please take a look.

### CODE REVIEW

**Comment by kortschak** [comment]
I should bump the Go versions for CI.

**Comment by vladimir-ch** [comment]
Ok, I'll bump the Go version too.

About `Drotg`, OpenBLAS seems to use their own C implementation in `interface/rotg.c` which is based on the previous reference version that doesn't handle extreme values well. I'll create an issue for them.

I'll check `Dlarfb` next.

**Comment by vladimir-ch** [comment]
The failure of `Dlarfb` test turns out to be a bug in LAPACKE: https://github.com/Reference-LAPACK/lapack/issues/877

**Comment by kortschak** [comment]
After running `go generate ./...` to bring the errors and doc synchronisation up to date the only failure locally is the known drotg issue.

**Comment by vladimir-ch** [comment]
I've run `go generate`. I think OpenBLAS will pick up the fix for the Dlarfb issue but the Drotg issue will likely persist. Should I add a flag to skip testing huge numbers from this repo?

**Comment by kortschak** [comment]
Yeah, I think so.

**Comment by vladimir-ch** [comment]
I missed there's one more failure in Drotmg:
```
=== RUN   TestDrotmg
    level1double.go:2206: drotm y_0 mismatch RD1_Med_RD2_Big_Flag_0: expected 0, found 5.1194107541670215e-11
--- FAIL: TestDrotmg (0.00s)
```

**Comment by vladimir-ch** [comment]
The root cause is again the difference between using and not using FMA. The detection of the FMA instruction in the CI pipeline gives different results from running locally. It'd be nice to know how to get the same (or at least in terms of FMA) build in both environments. Anyway, I'll see if I can either improve the test or relax the tolerance.

**Comment by vladimir-ch** [comment]
"All checks have passed" :tada:

**Review by kortschak — APPROVED** [review]

**Pull request merged**
