### PR TITLE
blas/netlib: add docs and test for Ztpsv

### PR DESCRIPTION
**Pull request by vladimir-ch**
Please take a look.

### CODE REVIEW

**Comment by vladimir-ch** [comment]
I expect the tests to fail due to Drotmg.

**Comment by kortschak** [comment]
Not quite. It did not pull the change from gonum/donum and it complains about the amount of work for Dbsqr - I checked that and it matched. I've restarted the build in the hope that it pulls the new gonum/gonum and we can go from there.

**Comment by kortschak** [comment]
It's still failing there - I don't understand why, it's passing locally.

**Comment by kortschak** [comment]
Ah, I understand now, this branch start prior to the change to `Dbdsqr`. A rebase onto master would fix the build, but it's not necessary.

**Comment by vladimir-ch** [comment]
I'm glad you found it. I opened the travis log and my eyes crossed.

**Pull request merged**
