### PR TITLE
modules,lapack/netlib: update for gonum v0.11.0 and add Dpstrf

### PR DESCRIPTION
**Pull request by vladimir-ch**
Getting back to the neglected netlib repo. This PR replaces and closes https://github.com/gonum/netlib/pull/84. Let's see what tests will fail, locally I'm getting a failure in Drotg.

Please take a look.

### CODE REVIEW

**Comment by vladimir-ch** [comment]
Before I start looking at the failures, @kortschak could you please help me with updating the CI pipeline?

**Comment by kortschak** [comment]
Would you like me to do that in another PR?

**Comment by vladimir-ch** [comment]
I don't have a preference, another PR is fine. Thanks.

**Comment by vladimir-ch** [comment]
I forgot this PR existed. Closing because superseded by #92 .

**Pull request closed without merging**
