### PR TITLE
blas/netlib: enable test for Ztbmv and Ztbsv

### PR DESCRIPTION
**Pull request by vladimir-ch**
Please take a look.

### CODE REVIEW

**Comment by vladimir-ch** [comment]
This PR failure is because I got ahead of myself and enabled the test for Ztbsv which does not exist yet in the gonum repository. It will come in the next PR.

The Dbdsqr failure is strange, it must be something with your local setup/version.

**Comment by kortschak** [comment]
I've rebuilt OpenBLAS and that goes away, but now I get a failure in `Dtrmm`.

```
=== RUN   TestDtrmm
--- FAIL: TestDtrmm (0.00s)
	dtrmm.go:803: Case 16. Want [20 128 314 26 164 398 32 200 482 38 236 566], got [20 128 832 26 164 1078 32 200 1324 38 236 1570].
	dtrmm.go:803: Case 17. Want [20 128 314 26 164 398], got [20 128 832 26 164 1078].
	dtrmm.go:803: Case 18. Want [20 62 194 26 80 248 32 98 302 38 116 356], got [20 62 832 26 80 1078 32 98 1324 38 116 1570].
	dtrmm.go:803: Case 19. Want [20 62 194 26 80 248], got [20 62 832 26 80 1078].
	dtrmm.go:803: Case 20. Want [136 208 144 172 262 180 208 316 216 244 370 252], got [136 208 0 172 262 0 208 316 0 244 370 0].
	dtrmm.go:803: Case 21. Want [136 208 144 172 262 180], got [136 208 0 172 262 0].
```

**Comment by vladimir-ch** [comment]
> ... now I get a failure in Dtrmm

Sorry, I can't reproduce that either.

**Comment by vladimir-ch** [comment]
PTAL

**Comment by vladimir-ch** [comment]
_ping_

**Comment by vladimir-ch** [comment]
No problem, I just want to make Travis happy.

**Pull request merged**
