### PR TITLE
modules: update for gonum v0.9.0

### PR DESCRIPTION
**Pull request by kortschak**
Please take a look.

### CODE REVIEW

**Comment by kortschak** [comment]
Passes locally, still fails on remote build infrastructure.

**Comment by vladimir-ch** [comment]
I'm not sure it's correct in DrotmgTest to multiply `y` from Drotm with `rd2` from Drotmg. Not multiplying won't turn it into 0 but the result will be 3 orders smaller (~1e-14) which is easier to accept as zero.

In the Dlapy2 test I think we'll have to use a tolerance in the test instead of strict equality.

**Comment by kortschak** [comment]
Do you want to fix those in testblas/testlapack?

**Comment by vladimir-ch** [comment]
Sorry, I misunderstood, my previous comment is wrong. But now I'm wondering whether the test should pass {sqrt(d1)*x1, sqrt(d2)*y1} to Drotm instead of {x1,y1} and multiplying afterwards. But if the failure can only be reproduced on GitHub and we have to push to gonum repo and run the test in this repo, the test cycle is very long and unconvenient ...

**Comment by kortschak** [comment]
In situations like this, I'd do experiments in this repo in the PR with a temporary copy of testblas in this repo. Still slow, but not quite as horrific is handling two modules and requiring replaces in the go.mod.

**Comment by vladimir-ch** [comment]
Closing because superseded by #92. I will handle any remote build failures there.

**Pull request closed without merging**
