### PR TITLE
blas/netlib: update generated docs

### PR DESCRIPTION
**Pull request by kortschak**
Please take a look.

Fixes build.

### CODE REVIEW

**Comment by kortschak** [comment]
This is failing because of the travis cache. I'm going to leave it for a bit and see how we go.

/cc @jonlawlor

**Comment by vladimir-ch** [comment]
How is this doing?

**Comment by kortschak** [comment]
Restarted tests.

**Comment by kortschak** [comment]
Well, something is very seriously wrong. The first Go version in the matrix errors because of this:

```
# gonum.org/v1/gonum/lapack/testlapack
../gonum/lapack/testlapack/dgeev_bench.go:51: b.Run undefined (type *testing.B has no field or method Run, but does have testing.run)
?   	gonum.org/v1/netlib/lapack/lapacke	[no test files]
FAIL	gonum.org/v1/netlib/lapack/netlib [build failed]
```

**Pull request merged**
